package com.xor.model;

import java.util.Date;

public class DiscussPost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.id
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.content
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.discuss_id
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    private Integer discussId;
    
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.student_id
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.record_time
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    private Date recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.id
     *
     * @return the value of discuss_post.id
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.id
     *
     * @param id the value for discuss_post.id
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.content
     *
     * @return the value of discuss_post.content
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.content
     *
     * @param content the value for discuss_post.content
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.discuss_id
     *
     * @return the value of discuss_post.discuss_id
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    public Integer getDiscussId() {
        return discussId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.discuss_id
     *
     * @param discussId the value for discuss_post.discuss_id
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    public void setDiscussId(Integer discussId) {
        this.discussId = discussId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.student_id
     *
     * @return the value of discuss_post.student_id
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.student_id
     *
     * @param studentId the value for discuss_post.student_id
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.record_time
     *
     * @return the value of discuss_post.record_time
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.record_time
     *
     * @param recordTime the value for discuss_post.record_time
     *
     * @mbg.generated Sun Oct 20 12:01:45 CST 2019
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    
   }

	public String getStudentName() {
		return studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}
    
    
}